# Generated by Django 5.0.6 on 2024-05-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0014_alter_attendancemaster_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancemaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='citymaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='companydetails',
            options={},
        ),
        migrations.AlterModelOptions(
            name='departmentmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='designationmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeedepartment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeedesignation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeeimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeejoinmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeemaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='nationmaster',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statemaster',
            options={},
        ),
        migrations.AlterModelTable(
            name='attendancemaster',
            table='AttendanceMaster',
        ),
        migrations.AlterModelTable(
            name='citymaster',
            table='CityMaster',
        ),
        migrations.AlterModelTable(
            name='companydetails',
            table='CompanyDetails',
        ),
        migrations.AlterModelTable(
            name='departmentmaster',
            table='DepartmentMaster',
        ),
        migrations.AlterModelTable(
            name='designationmaster',
            table='DesignationMaster',
        ),
        migrations.AlterModelTable(
            name='employeedepartment',
            table='EmployeeDepartment',
        ),
        migrations.AlterModelTable(
            name='employeedesignation',
            table='EmployeeDesignation',
        ),
        migrations.AlterModelTable(
            name='employeeimage',
            table='EmployeeImage',
        ),
        migrations.AlterModelTable(
            name='employeejoinmaster',
            table='EmployeeJoinMaster',
        ),
        migrations.AlterModelTable(
            name='employeemaster',
            table='EmployeeMaster',
        ),
        migrations.AlterModelTable(
            name='nationmaster',
            table='NationMaster',
        ),
        migrations.AlterModelTable(
            name='statemaster',
            table='StateMaster',
        ),
    ]
